# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - camel_case_types
    - empty_catches
    - empty_constructors
    - implementation_imports
    - library_names
    - library_prefixes
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - prefer_void_to_future_void
    - type_init_formals
    - unnecessary_statements
    - unrelated_type_equality_checks

analyzer:
  exclude:
    - "**/*.g.dart"
  errors:
    # Ignore missing_required_param errors
    missing_required_param: ignore
    # Ignore undefined_class errors in packages
    undefined_class: ignore
